### PR TITLE
Added data extracts to avoid creating tasks with no features

### LINKED ISSUE #37: Creating task areas with no features should not be possible
**Describe the bug**

- This is specific to the **split by square** algorithm.
- It's possible that sometimes a task area is generated with no features inside it.
- This happens when an AOI is not square.

**To Reproduce**

Project https://fmtm.hotosm.org/project/100

**Expected behavior**

- The task areas with no features are deleted at the end of the `split_by_square` function to avoid this problem.

**Screenshots**

You can see two small task areas that have no buildings:
image

**Additional considerations**

I imagine this problem does not exist on the complex splitting algorithm, as we handle the case already.

### PR DESCRIPTION
**Pull request by Sujanadh**
## Issue:
- fix #37 

## Updates:
This PR now avoids creating tasks with no features in them when the AOI is splitted using the `split_by_square` algorithm. 

- Data extracts are now passed to the logic in order to check if a task has any features in it or not. In case a task does not have osm features inside it , it won't be appended to the list of tasks generated by the algorithm.

### CODE REVIEW

**Comment by spwoodcock** [comment]
The split by square tests are failing as I assume they need the data extract passed to them.

Once fixed, I will merge and create a new release, then update fmtm-splitter on https://github.com/hotosm/fmtm/pull/1642 👍

**Comment by spwoodcock** [comment]
Nice work by the way 😄

**Review by spwoodcock — APPROVED** [review]

**Comment by Sujanadh** [comment]
These pre-commit hooks aren't being installed on my system, failing every time.

**Comment by spwoodcock** [comment]
No worries about the failing pre-commit tests here! They are failures linting the additional SQL files in the repo - I should set an exclusion 👍 

To install the pre-commit hooks so they always run on the repo locally:

```bash
pip install pre-commit
pre-commit install
```

The hooks will run every time you try to commit and not allow you to commit if there are failures.
If you need to commit anyway despite errors, use the `--no-verify` flag:

```bash
git commit -m "fix: some fix" --no-verify
```

**Pull request merged**
