### PR TITLE
Updated algorithm to split aoi when no linear features

### LINKED ISSUE #29: Error handling if no linear features are included in data extract
**Describe the bug**

- If no linear features (road, river, etc) are included in the data extract used for splitting, then the SQL can fail silently.
- This means no features are returned as there was an error.

**To Reproduce**

- Test in FMTM project creation with a building-only data extract.

**Expected behavior**

- The algorithm should simply cluster buildings into approximate groups based on the number of average buildings.

### LINKED ISSUE #32: Limit the choices to only major important highways
**Is your feature request related to a problem? Please describe.**

We are considering every highway while splitting, which results into smaller polygons(tasks) regardless of number of buildings(no clustering only filling buildings to splitted polygons).

**Describe the solution you'd like**

We should only consider the highways that will obstruct field mappers or will be difficult for them to come back and forth the road.

**Describe alternatives you've considered**

Filtering only the major highways by not considering smaller roads such as residential, unclassified , pedestrian roads and so on.

**Additional context**

simple example can be :
```
splitlines AS (
      SELECT ST_Intersection(a.geom, l.geom) AS geom
      FROM aoi a
      JOIN "ways_line" l ON ST_Intersects(a.geom,        l.geom)
      WHERE (
          (l.tags->>'highway' IS NOT NULL AND 
          l.tags->>'highway' NOT IN ('unclassified', 'residential', 'living_street', 'service', 'pedestrian', 'track', 'bus_guideway'))
          OR l.tags->>'waterway' IS NOT NULL
          OR l.tags->>'railway' IS NOT NULL
      )
  )
```

### PR DESCRIPTION
**Pull request by Sujanadh**
## Changes
- refactored existing algorithm to allow splitting the aoi when no linear features are present by clustering according to the number of buildings used
- used k-means clustering

## Issue
- Fixes #29 
- Fixes #32
- Fixes https://github.com/hotosm/fmtm/issues/1151 by another means, with https://github.com/hotosm/fmtm-splitter/issues/24 still pending

### CODE REVIEW

**Comment by Sujanadh** [comment]
- looking for other issues to solve

**Comment by Sujanadh** [comment]
I think i overdid the clustering twice, so removed it.

**Comment by Sujanadh** [comment]
- simplified the task boundaries; related to [#1151](https://github.com/hotosm/fmtm/issues/1151)
- removed hardcoded buildings number

**Comment by Sujanadh** [comment]
- fixes #32

**Review by spwoodcock — APPROVED** [review]

**Comment by spwoodcock** [comment]
This is excellent work. 

I just fixed the tests. 
The update also also appears to have fixed an issue where some task areas were generated as multipolygons (i.e. with holes) 👍 
It mainly reduces the number of task areas generated, which is likely a good thing (as the buildings are better distributed amongst areas).

Merging 🎉

**Pull request merged**
