### PR TITLE
Merge polygons smaller than 35% of perfect square polygon to neighbouring polygon

### PR DESCRIPTION
**Pull request by Sujanadh**
## Issue:
- Related Issue: https://github.com/hotosm/fmtm/issues/1960

## Description:
Smaller polygons are detected based on their area, which is less than 35% of the area of the square. The neighbouring polygons are determined by who shares the larger boundary and is nearest to the small polygons. Then those smaller polygons are merged to their respective neighbouring polygons.

## Screenshot:
Before:

image

After:

image

Those gaps within the tasks are because they do not contain any features within them.

### CODE REVIEW

**Comment by spwoodcock** [comment]
This is an excellent change, thanks @Sujanadh !

Obviously with using PostGIS, this puts a hard requirement on having a database for splitBySquare.
I messaged @robsavoye about it (who is also using fmtm-splitter) & even though it's a huge pain for him, he said it's ok and we should forge ahead.

So apologies once again @robsavoye !

This move to using PostGIS spatial queries is part of a longer term goal:
- Remove Python dependencies like shapely.
- In the long run, we can use the PostGIS queries directly in the web browser via PGLite (saving a backend API call entirely).

**Comment by spwoodcock** [comment]
Also, I should note, for anyone wanting to use splitBySquare without a database, then pin the version `fmtm-splitter<2`.

We will increment the version to 2.0.0 here, as it's a breaking change in semver.

**Comment by rsavoye** [comment]
You can probably drop #72, as I'll have to drop using fmtm-splitter. Personally adding postgres as a dependency to replace shapley is a bit overkill, but I understand the other functionality FMTM needs. I'm not building a website, so my task splitting needs are different.

**Review by spwoodcock — APPROVED** [review]
Good stuff 🚀 

In the future we can probably refactor out the shapely box() usage and do this in PostGIS too 👍 

I will make a new release with this

**Comment by spwoodcock** [comment]
Oops, forgot to check the tests!

It makes sense the tests would have broken with this change, but let's try and keep them working 🙏

**Comment by Sujanadh** [comment]
Okay :+1:

**Comment by spwoodcock** [comment]
I planned to fix the tests the other day, but I'm really running out of time before Christmas (have some other things being asked of me too).

Sorry to ask @Sujanadh, but could you fix the tests here whenever you get a chance please? 🙏 Anuj could get involved if it helps

**Comment by Sujanadh** [comment]
Sorry, I totally forgot to fix the tests. I will fix it  :+1:.

**Comment by spwoodcock** [comment]
Hate to be pedantic 😂 but I know I will forget eventually too!! (was still in my github notifications for now)

**Pull request merged**
